model:
  model_filename: /nfs/diskstation/projects/mech_search/siamese_net_models/feature_l1_test_new20180830T1315/feature_l1_test_new_0006.h5
  input_shape: [512, 512, 3]
  weights: imagenet
  two_gpus: 1
  distance_metric: l1
  include_reg: 0

benchmark:
  dataset_path: /nfs/diskstation/projects/mech_search/siamese_net_training/phoxi_training_dataset
  test_cases: 100
  batch_size: 8
  vis_output: 0
