model:
  model_filename: /nfs/diskstation/dmwang/mech_search_siamese_models/full_images_dataset/best_model20181024T2052/mask_rcnn_best_model_0007.h5
  # input_shape: [512, 512, 3]  # Use this for image-based model.
  input_shape: [9984] # Use this for feature-based model.
  use_triplet_embedding: 0
  triplet_embedding_layer_sizes: [2048, 1024, 512]
  triplet_embedding_network_weights: '/nfs/diskstation/dmwang/mech_search_siamese_models/embedding_models/first_attempt.h5'
  input_type: features  # images or features.
  weights: imagenet
  two_gpus: 0
  distance_metric: l1
  include_reg: 0
  use_distance_network: 1
  distance_network_layer_sizes_before_concat: [1024]
  distance_network_layer_sizes_after_concat: [512, 256]

train:
  dataset_path: /nfs/diskstation/projects/mech_search/siamese_net_training/phoxi_training_dataset
  dataset_type: features # images or features
  learning_rate: 0.0001
  weights: imagenet # imagenet, last, or random
  epochs: 5
  batch_size: 64
  shuffle_training_inputs: 1
  num_train_pairs: 1000
  num_val_pairs: 100
  # data_augmentation_suffixes: ['', '_rotate_and_scale']
  data_augmentation_suffixes: ['']
  allow_different_views: 1  # For positive examples.
